name: SSE E2E

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install Node deps
        run: |
          npm ci || npm install

      - name: Install Frontend deps
        run: |
          npm --prefix frontend ci || npm --prefix frontend install

      - name: Lint Frontend
        run: |
          npm run sse:lint

      - name: Install Playwright browsers
        run: |
          npx playwright install --with-deps chromium

      - name: Run SSE E2E
        env:
          PORT: 8000
        run: |
          bash scripts/sse-ci.sh

      - name: Upload Playwright report (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: |
            playwright-report
            webapp/e2e/playwright-report
          if-no-files-found: ignore

      - name: Upload Playwright test-results (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-results
          path: |
            test-results
            webapp/e2e/test-results
          if-no-files-found: ignore
